services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15433:5432'
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - 'POSTGRES_USER=test_user'
      - 'POSTGRES_DB=example_db'
      - 'POSTGRES_PASSWORD=secret'
  server:
    image: tink-dz1:latest
    ports:
      - "8080:8080"
    environment:
      - 'DB_HOST=database'
      - 'DB_NAME=example_db'
      - 'DB_USERNAME=test_user'
      - 'DB_PASSWORD=secret'
      - 'DB_PORT=5432'
volumes:
  db_data:
    driver: local