services:
  database:
    image: 'postgres:15.2'
    ports:
      - '15433:5432'
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - 'POSTGRES_USER=test_user'
      - 'POSTGRES_DB=example_db'
      - 'POSTGRES_PASSWORD=secret'
  storage:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    ports:
      - '9001:9000'
    environment:
      - 'DB_HOST=database'
      - 'DB_NAME=example_db'
      - 'DB_USERNAME=test_user'
      - 'DB_PASSWORD=secret'
      - 'DB_PORT=5432'
      MINIO_ROOT_USER: test-user
      MINIO_ROOT_PASSWORD: secret-secret
    command: "server /data"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
#  server:
#    image: tink-dz1:latest
#    ports:
#      - "8080:8080"
#    environment:
#      - 'DB_HOST=database'
#      - 'DB_NAME=example_db'
#      - 'DB_USERNAME=test_user'
#      - 'DB_PASSWORD=secret'
#      - 'DB_PORT=5432'
volumes:
  db_data:
    driver: local
  minio_data:
    driver: local